server:
  port: 9001
spring:
  application:
    name: tensquare-base #指定服务名
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/tensquare_base?characterEncoding=utf-8
    username: root
    password: rootzs
  rabbitmq: 
    host: 192.168.0.110
jwt:
  config:
    key: zshuai
  jpa:
    database: mysql
    show-sql: true
    # generate-ddl: true # 控制是否执行datasource.schema脚本，来初始化数据库结构
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true
ip: 127.0.0.123
