server:
  port: 9006
spring:
  application:
    name: tensquare_spit
  data:
    mongodb:
      host: 192.168.0.111
      database: spitdb
    redis:
      host: 192.168.0.111
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true